data_dir = "../../data"
multiclass_data_dir = "../../data/multiclass"
multilabel_data_dir = "../../data/multilabel"

genres = [
    "pop", 
    "rock", 
    "r-b", 
    "country", 
    "rap", 
    "blues", 
    "jazz", 
    "experimental", 
    "folk", 
    "classical-music", 
    "electronic"
]